name: Docker Builder

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'v4-dind'
          - 'v5-dind'
    steps:
      - uses: actions/checkout@v4
      - name: Build Image V4
        run: docker build -t mygento/deployer:${{ matrix.version }} -f BuilderV4.Dockerfile .
        if: matrix.version == 'v4-dind'
      - name: Build Image V5
        run: docker build -t mygento/deployer:${{ matrix.version }} -f BuilderV5.Dockerfile .
        if: matrix.version == 'v5-dind'
      - name: Test Vault
        run: docker run --rm mygento/deployer:${{ matrix.version }} vault -v
      - name: Test Nomad
        run: docker run --rm mygento/deployer:${{ matrix.version }} nomad -v
      - name: Test Levant
        run: docker run --rm mygento/deployer:${{ matrix.version }} levant -v
      - name: Test Nomad Pack
        run: docker run --rm mygento/deployer:${{ matrix.version }} nomad-pack version
      - name: Test Gomplate
        run: docker run --rm mygento/deployer:${{ matrix.version }} gomplate -v
      - name: Test PHP
        run: docker run --rm mygento/deployer:${{ matrix.version }} php -v
      - name: Test Composer
        run: docker run --rm mygento/deployer:${{ matrix.version }} composer -V
      - name: Test Composer Config
        run: docker run --rm mygento/deployer:${{ matrix.version }} composer config --list --global
      - name: Test node
        run: docker run --rm mygento/deployer:${{ matrix.version }} /usr/bin/node -v
      - name: Test Deployer
        run: docker run --rm mygento/deployer:${{ matrix.version }} deployer -V
      - name: Test npm
        run: docker run --rm mygento/deployer:${{ matrix.version }} npm -v
      - name: Test yarn
        run: docker run --rm mygento/deployer:${{ matrix.version }} yarn -v
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push image
        run: |
          export IMAGE_NAME=mygento/deployer:${{ matrix.version }}
          export IMAGE_ID=ghcr.io/luckyraul/deployer:${{ matrix.version }}

          # Change all uppercase to lowercase
          export IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo $IMAGE_ID

          docker tag $IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
      - name: Push image Mygento
        run: |
          export IMAGE_NAME=mygento/deployer:${{ matrix.version }}
          export IMAGE_ID=ghcr.io/mygento/deployer:${{ matrix.version }}

          # Change all uppercase to lowercase
          export IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo $IMAGE_ID

          docker tag $IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
